name: Deploy

on:
  workflow_call:
    inputs:
      workspace_name:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      workspace_name:
        type: choice
        required: true
        options:
          - greet
          - hello-ca

jobs:
  artifact:
    name: Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo "${{ github.event.inputs.workspace_name }}"
