name: Deploy

on:
  workflow_call:
    inputs:
      workspace_name:
        type: string
        required: true

jobs:
  artifact:
    name: Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo "${{ github.event.inputs.workspace_name }}"
