name: Deploy

on:
  workflow_call:
    inputs:
      workspace_name:
        type: string
        required: true
      version:
        type: string
        default: "latest"
  workflow_dispatch:
    inputs:
      workspace_name:
        type: choice
        required: true
        options:
          - greet
          - hello-ca
      version:
        type: string
        default: "latest"

jobs:
  artifact:
    name: Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Reduce monorepo to ${{ inputs.workspace_name }}
        run: |
          corepack enable 
          yarn workspaces focus
          yarn turbo prune ${{ inputs.workspace_name }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: ./out/yarn.lock

      - name: Build ${{ inputs.workspace_name }}
        run: |
          yarn config set nodeLinker node-modules
          yarn install --immutable
          yarn build
        working-directory: ./out
